name: Build Assets

on:
  pull_request:
    branches: [ master, main ]
  workflow_call:

jobs:
  build:
    name: Install dependencies 
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - name: To checkout repo 
      uses: actions/checkout@v2

    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14.x
    
    - name: Install dependencies
      run: npm ci
